package tesl.rest.reader

import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import java.io.ByteArrayInputStream
import java.io.File
import javax.imageio.ImageIO

class CollectionImageCreatorTest {
    @Disabled("writes real data")
    @Test
    fun `can create a collection image`() {
        val collectionCode = "SP\"bbkwjwWrzafbneTeElsaeohylwAkCrguGjghLcteArtputBtfkMrdrhyAuthmtPonyaaonRlHaEjFgFeaxgejxDnUeivZgRtpbLfecdlRpGmUlpoUbPnmqrwJcDajoBqtbjkurHmxiOfcrVkPcTckvSaJjKdSeyqptDlnmOjPijpNfCjWuxsjgKoAhZbqekcziXtwqqsZkBigaAypddnvbzxBgOiJsxsIjBuwcmmKanwYpctzvAlKwQjthMoXqApPkqgDqYaspXbExGxCjQffqnqehiwbmrlklamXvYxUhRxhjVqonFjaqc!ffmiPbwhegWeBgLqjkjfZgxuukAmdgbmgwyxLforqfQhrnOdbqIlvrrmefzbTgBshbRyGiloreulxhTelmzeroKxdpMdAiMkakRnDjAgAdrbdkhlfsghPaHrRrOjehDfdavfIbulgdX*YedgPoWqkgElelbtMtQhnxMwzmtpWaNgSfMrGazgZghoQbQbfxbePfswppibXiLwDwxkogujxhdgmechfksfthYospSytfSmEsfiBiNoMqBmJrBlPronVgyxjadpTbptglQtxmixWqljRrLagovvLlinleGtnrluFyClZoZauwvkvmkxSevmjoysemInMtCeDbyxrjhvKsvxQcskffEebiysdqiaDqFvEgcqsacudkVducEthxFjUoGvOaBgYeOpEqKoodVphxkimsHiCwcmpvGrTjOsXmldyeqrfxAnTmacFwaiwpZiDrybcayiHsLwFpIqgcJuzjssyxwmYaXtafnmSjbqOpHrIbgbAitihwNhxkYchnojDglcrcGgGuhcSpstvpwrAbOcBkLgzmBdvdWgIydvBraxxoDeKdlqLmhrCfucfiEwwwXlhnYyitbdBjMaVhlcyrvcZlCwrdKisakuluolwvNhuivbxjpaTcxoPkJhUmRbYtlnjquiayjabgJtimGwBvVsasYmDlYiIojsQoesAnXrcpBoigaoOcnrZjknakeoxnEmfkXqfdOcunBwikIwqaUfwfNqTcIqPiqdpkZsWsJeziZsRfDnLxopbarxneJrMbBoteoowdIoliAhsgQpQlqlMeegCbooVkQrkjyhEbHqWhQaPlAhJwMyFfGxyuqcMuvepfllyomiomPurfPyrhhmFbvhgwgsUiSaFwtyvuCkgjmpxwufxlWoSjGemnpyqnHgsslnhxceXmCofdsdgpdkcpzoqsVdJqvfRdoxtwhfWhwrigThWfrfijjeNdYeRzCcUhbjHoazBrjiWoEngcgkrwkiYceldaRjwoppveQdqnGcqpFtOppiQahmLxNvUxPdGjEgUgpvRnuhNujwflDjitmwLhtqGiGjYwlxsvCclwdkEmqbFnPmmcXymcbjJaIxEaKktprcRcvwCygvHjqbhgeiKtuternaCwnnsbWqUsPxVdCwStSupokgtdhyhhjfavXdPxzdTptyJfFxpesqdbNeMntynbJkitqwVxZirccfTdQnywEyfmwbKsFhIwItdklwGhFywruwsaObtcVdFmWdEwevDfkkSpquBysvTdRkxlTcPoJhHjSmTybzAugozeFeIcChvxRqJnzhXnfxuspbGtHfqhOcKqElLsKkysEuAgvcpmnikdefBtjoRyEtorbaWenbrgnpRfYehrDsbrpmQsirFoIljpDknfAtFbSdntGgwltgincbUkNmoiubereeZkpdmniichBcQaMeVtAtstRrseSrXgojrunxismtccwtEyowRuscodUiiqSqNkGvWrElGnbbZlOgMxmyywoexdDkWxTnCyxvMvJlExvkHjTjopysGqxyDsOeHlryVkdhzlXpUrPkkuDyurKhVqwfJhSkDdkrQholJpolVqQlIhctknSwUqzgqwKjXvFlmjLbDxHfhaivPqDjnsCumnKxYwTdZttdjoTnwskvIvQjCcjqawZixfUmNuEdanIpafboubCeYswuekzdMhaqHsDocxlawfLmHnxqhndnAukrWpeeflzciqbcOqCcagdtramqXlcpOdzgHyksMtIqmibjvoLkbbmfvjNaQwOogmZmcwHoYplgjdLpLtyxqalcNneqRkUsThyfpfVbinrtNblnZmVkTobbsdfhCsSlBnNpCpVwPrYxImyxepmqysNwmdHnQgkhkbMtL"

        val array = CollectionImageCreator().createImage(collectionCode)
        val image = ImageIO.read(ByteArrayInputStream(array))
        ImageIO.write(image, "PNG", File("/home/markf/dev/personal/gaming/collection.png"))
    }
}